# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_auto_20190405_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_site',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
